### PR TITLE
Return validation responses as JSON

### PR DESCRIPTION
**Pull request by 13ROY**
Return a validation response with details and as JSON instead of html

### CODE REVIEW

**Comment by samc621** [comment]
@13ROY I like this suggestion, I was thinking of adding `express-validation` on each endpoint, but I never got around to it. Can you paste a sample output?

**Comment by 13ROY** [comment]
Hi @samc621 , yes a sample output is:

```
{
    "name": "ValidationError",
    "message": "Validation Failed",
    "statusCode": 400,
    "error": "Bad Request",
    "details": {
        "params": [
            {
                "message": "\"id\" must be a number",
                "path": [
                    "id"
                ],
                "type": "number.base",
                "context": {
                    "label": "id",
                    "value": "ab",
                    "key": "id"
                }
            }
        ]
    }
}
```

Placing this where I have means all endpoints will inherit this behavior and return json responses for validation errors.

**Comment by samc621** [comment]
Thanks for adding the output. The way the API currently works, it returns the `err.message`, which in the case of a `ValidationError` would just be `Validation Failed` and is not particularly useful to the user. I like the idea of including this full JSON instead, it's much more useful. 

I can easily do this by including it in the `data` key of the response. I would prefer to do it in the API controllers themselves, or in the `ServerResponse.js` file than in `app.js` - this file seem like the wrong place for such logic.

**Comment by 13ROY** [comment]
Hi @samc621 , I agree that the `app.js` is not the best place to keep the validation logic, and having a handler for each controller would allow for a little more control of the output.
I have subsequently done the necessary changes, although they work I am not completely happy with the duplication of the validation handler code in all `validation.js` files (though I know they could change/vary in the future), and the need to include the validation handler for each route call.
I could create a separate validation handler file that would then become a shared reference for all index.js, but I feel we'd be moving the validation further away from where it belongs.
Take a look over it and let me know how you feel, I was hoping there would be a better solution that required less changes to so many files. My experience with Node.js is limited so you may be able to offer an alternative method?

**Comment by samc621** [comment]
Hi @13ROY nice work here! I was thinking about it a bit, and I think this is probably the best we are going to get for now. Because this middleware needs to come after the validation on the specific route, I don't see where we can move it. If anything, maybe just make a helper for the `validationHandler` middleware instead of implementing it in each `validation.js` file. Also, I think the `ValidationError` can be caught before the controller function is called, right? So we can switch the error of the middleware so that it comes after the `validate()` call but before the controller function is called.

**Comment by 13ROY** [comment]
Hi @samc621 , I agree with the order of validation and have changed it. I did concede and create a shared validation handler, I am still considering ripping out the validation handlers from all the `validation.js` files and directly referencing it in the `index.js` files.
Let me know what you think and hopefully we can get this approved!

**Review by samc621 — APPROVED** [review]
@13ROY nice work here as well, thanks for the updates!

**Pull request merged**
