### PR TITLE
Remove lint issues

### PR DESCRIPTION
**Pull request by 13ROY**
Updates the integration tests coverage and introduces a mock database when testing.
Refactored the code to reduce duplication and remove some error messages found in the console.

NB: This replaces PR https://github.com/samc621/SneakerBot/pull/36 (which I have closed)

### CODE REVIEW

**Comment by samc621** [comment]
@13ROY this is awesome, thank you! One question, why was the generic validation handler removed? Wasn't this necessary for properly throwing validation errors?

**Comment by 13ROY** [comment]
@samc621 the generic validation handler wasn't removed, it was just moved to the routers ;)
It might be beneficial to add tests for the validation, but that's for another day.

**Review by samc621 — APPROVED** [review]
@13ROY I see that now, sorry! This LGTM!

**Comment by samc621** [comment]
@13ROY looks like some of the tests are [failing](https://github.com/samc621/SneakerBot/actions/runs/1247560300), can you take a look when you get a chance?

**Comment by 13ROY** [comment]
Yep, I've taken a look and figured out the problem, it turns out mock-knex is not a true db mock, but requires a db to exist (and the CI environment does not have this), so I can do one of 2 things:
1. Use `knex-mock-client` - this should allow me to mock the db (and give a little more control and clarity over what functions I am mocking)
2. Use an actual in memory database (such as `pg-mem`), this will require a rewrite

My intention is to go with option 1, I ran out of time today but hopefully will have some time tomorrow to get this done.

**Comment by samc621** [comment]
@13ROY yes this makes sense and I agree that option 1 should be best for now.

**Pull request merged**
